services:
  fold:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    devices:
      - nvidia.com/gpu=all
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia.com/gpu
    #           count: all
    #           capabilities: [gpu]
    volumes:
      - ../data:/fold/data:ro,z
      - ../data/models:/fold/data/models:z
      - ../.cache:/fold/.cache:z
      - ../cache:/fold/cache:z
    command: /bin/bash
    stdin_open: true
    tty: true
